#!/usr/bin/env bash
# install nginx server

# install
sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

# testing
sudo nginx -t

sudo service nginx reload
