#!/usr/bin/env bash
# redirecting to another page

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

str_for_replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/githup.com\/Tarek123Gaml permanent;"

sudo sed -i "s/server_name _;/$str_for_replace/" /etc/nginx/sites-available/default

sudo service nginx restart
