#!/usr/bin/env bash

# Install HAProxy
sudo apt-get update
sudo apt-get -y install haproxy

# Configure HAProxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 486627-web-01 35.153.66.82:80 check
    server 486627-web-02 54.237.99.70:80 check
EOF

# Restart HAProxy service
sudo systemctl restart haproxy

# Enable HAProxy to be managed via init script
sudo systemctl enable haproxy

# Verify HAProxy status
sudo systemctl status haproxy

exit 0
