#!/usr/bin/env bash

# Function to clean up and exit
cleanup_and_exit() {
    echo "Deleting PID file and terminating script..."
    rm -f /var/run/myscript.pid
    exit
}

# Trap signals
trap 'echo "I hate the kill command" && exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'cleanup_and_exit' SIGQUIT

# Get the PID and save it to the file
echo $$ > /var/run/myscript.pid

# Display the message indefinitely
echo "To infinity and beyond indefinitely"

# Wait for signals
while true
do
    sleep 1
done

